### PR TITLE
Addition of install/uninstall scripts to create an elevated scheduled task for auto start on login and to bypass UAC

### PR DESCRIPTION
**Pull request by timberrr**
Install scripts would need running as an administrator but once installed the scheduled task should run correctly as an elevated user and avoid UAC prompts for USBDeview. Uninstall script will remove the scheduled task only, then advise a reboot (I'm sure this could be improved to also kill any relevant running processes).

Also due to addition of these install scripts, have moved runtime and other scripts into /bin just to keep the root tidy and make it clearer which files to run at first.

Hope this is ok!

### CODE REVIEW

**Comment by monstermac77** [comment]
This looks absolutely phenomenal. Thank you so much. I'll definitely be merging this in once I get a chance to review the code and maybe move some things around.

> (I'm sure this could be improved to also kill any relevant running processes).

I think this would be a great addition, because I know a lot of people have wanted to try turning MixedVR Manager off/on repeatedly and there's no easy way to do that now, but being able to run this "uninstall" script to both kill the process and stop it from starting on startup would be perfect. Any chance you could add this? You can always find the MixedVR Manager task by opening Task Manager, then adding the "Command Line" column, then scrolling down to the "Windows Command Processor" processes and find the one that has "MixedVR Manager" in the Command Line column.

Edit: also, as part of making it very easy for users to try turning MixedVR Manager off _and_ on, if the install script could start MixedVR Manager. That way basically "install" and "uninstall" start and stop it respectively, as well as obviously make this persistent across reboots.

**Comment by monstermac77** [comment]
Also, for when I get a chance to review these, it'd be helpful if you could just explain each of the files and how they fit together? I see there are a _lot_ of new files. I obviously understand the install/uninstall scripts and what they're doing, but I'd like to understand how all of the new files in the `bin` directory fit together.

**Comment by timberrr** [comment]
No worries I'll see if I can do something for that - and I'll add some more comments to the code and an overview here this evening :)

I am getting a weird issue with SteamVR giving an error updating (app running) now, and seemingly getting stuck in a loop (which I'm guessing is caused by the manager restarting SteamVR). What's odd is if I end the manager.bat process, SteamVR opens fine but shows no sign of needing to update (v 1.16.1 which appears to be the most recent version). Curious if you're getting the same when you have the chance to check?

**Comment by timberrr** [comment]
There's a couple of things I've realised I've done wrong here, sorry - I'm going to cancel the pull request while I fix my rubbish code :)

**Comment by monstermac77** [comment]
> I am getting a weird issue with SteamVR giving an error updating (app running) now, and seemingly getting stuck in a loop (which I'm guessing is caused by the manager restarting SteamVR). What's odd is if I end the manager.bat process, SteamVR opens fine but shows no sign of needing to update (v 1.16.1 which appears to be the most recent version). Curious if you're getting the same when you have the chance to check?

I've seen this occasionally/sporadically as well, although it doesn't manifest to me as SteamVR getting stuck in a loop for me. Independently, I have heard some people say SteamVR restarts in a loop sometimes with MixedVR Manager, but they usually don't mention SteamVR updating. 

> There's a couple of things I've realised I've done wrong here, sorry - I'm going to cancel the pull request while I fix my rubbish code :)

Certainly didn't look like rubbish! <3 Thanks again for your help. I'm very excited to kill that prereq and to make starting/stopping MixedVR Manager significantly more user friendly.

**Pull request closed without merging**
