### PR TITLE
Install/uninstall script, reorganised folders

### PR DESCRIPTION
**Pull request by timberrr**
Hi @monstermac77 , I think I've fixed the thing that was playing up (it looks like running with admin rights causes havoc with relative file calls, so I've added in an absolute path reference to the runtime now which looks to have sorted it.

Outline of new files:

- **install-mixedvr-manager.bat** - run as administrator (via regular context menu) and this will create a scheduled task with elevated permissions that will run on user login. The scheduled task passes the install folder filepath to the bat as an argument (this negates the issue with SCHTASKS not allowing variables and allows the VBS to then run successfully via absolute path - otherwise when run with admin permissions from a scheduled task the VBS runs with the working directory of C:\Windows\System32). It does NOT start the task up immediately; currently it just suggests a reboot on install - don't know if you'd want to add that but to get people up and running immediately rather than demanding a reboot.

- **remove-mixedvr-manager.bat** - run as admin again. This will kill the running background process if it's there, and remove the scheduled task. Recommends a reboot but it's probably not necessary since it kills the process.

- **bin/mixedvr-manager-startup.bat** - this is purely for the scheduled task as it seems to have issues running a VBS directly, can otherwise be completely ignored.

- Other changes: I moved everything apart from the readme, config.bat and the install/remove scripts into the bin folder to keep the root clear. Have also updated the main runtime (mixedvr-manager.bat) with absolute paths for all the script calls, as again with admin rights it seems to have issues with relative paths.

There still might be an issue if SteamVR is opened too quickly on boot, it seems to get caught in an error loop (though everything still eventually boots ok after just clicking ok on all the errors). Would be curious if you encounter the same issue. It was only attempting to open SteamVR very shortly (i.e. within a minute or so) of logging in. Possibly clashing with some Steam startup update checks?

### CODE REVIEW

**Comment by timberrr** [comment]
Oh also, as an aside I've started working on a system tray utility/context menu in C#/.NET to house this same rough process. Currently it's set up to manually start/stop lighthouses and HMDs, and all being well will allow some user friendly additions:

- Easy config form with validation for MAC addresses, lighthouse versions etc
- System tray icon and menu to monitor devices states, manual restarts, live enable/disable, logging, etc

Hopefully I'll stick a repo up soon (prob best doing a separate one as it's different enough, though it's still using the process you've put together so it'll clearly be a continuation of this!

**Comment by monstermac77** [comment]
Just wanted to say I haven't forgotten about this. I'm in the process of moving so my spare time has been a bit eaten up. I am very excited to review all this and merge it in!

**Comment by monstermac77** [comment]
>  It does NOT start the task up immediately; currently it just suggests a reboot on install - don't know if you'd want to add that but to get people up and running immediately rather than demanding a reboot.

I think we will want this just to make the install/uninstall process as "light" as possible. I'll try looking at doing this now. 

>  I moved everything apart from the readme, config.bat and the install/remove scripts into the bin folder to keep the root clear.

Very good call, I like the way you're thinking about this :) 

> Have also updated the main runtime (mixedvr-manager.bat) with absolute paths for all the script calls, as again with admin rights it seems to have issues with relative paths.

Oh boy, what a headache. Thank you for handling that.

> There still might be an issue if SteamVR is opened too quickly on boot, it seems to get caught in an error loop (though everything still eventually boots ok after just clicking ok on all the errors). Would be curious if you encounter the same issue. It was only attempting to open SteamVR very shortly (i.e. within a minute or so) of logging in. Possibly clashing with some Steam startup update checks?

Very interesting. I very rarely see these, and I usually start VR within 30 seconds of booting up, so I imagine I would see them. I'll let you know. Either way, it'd be nice to auto-kill these during the start-up/shutdown process anyway, so I might add that.

**Comment by monstermac77** [comment]
> Oh also, as an aside I've started working on a system tray utility/context menu in C#/.NET to house this same rough process. Currently it's set up to manually start/stop lighthouses and HMDs, and all being well will allow some user friendly additions:

Cool. Let me know how that's coming. 

> Easy config form with validation for MAC addresses, lighthouse versions etc

FYI hopefully before too long the whole manual MAC address entering stuff will be handled automatically by lighthouse-keeper per @rossbearman, see here: https://github.com/rossbearman/lighthouse-keeper/issues/2

**Comment by monstermac77** [comment]
Ok @timberrr so overall, this looks incredibly good. I had to get really nit-picky to come up with any changes at all. Well written and well documented. Thank you so much!

This is the only bug that I've found (trying to fix now, but so far I've had no luck): if there is a space in the path to MixedVR Manager, nothing works at all. Basically, task scheduler seems unable to start mixed-vr manager, and gives last run result `0x01` (you can see this in the task scheduler GUI). I've tested this pre and post all of my changes, and confirmed that the issue lies in there being a space in the path. I think this will occur for a lot of people, because many have their name (e.g. "C:/Cosmo Puccio/Documents/vr") in the path. It's pretty easy to test, just create a folder with a space in the name and then put your `vr` folder inside of it. If I figure it out, I'll comment here. Otherwise, assume I haven't figured it out and need your help!

**Comment by monstermac77** [comment]
Ok @timberrr I just sunk a bit over an hour _just_ trying to get things to work when you put the `vr` folder in a path that contains a space things actually work, but I couldn't figure it out. See above comment for more details. Things work flawlessly when the `vr` folder doesn't have a space in its path.

I'm hoping you'll be able to figure this out with fresh eyes. Literally _everything_ else is working perfectly and ready to push, lots of little enhancements that were enabled by your new install process, so I'm very excited to get this pushed out!

**Comment by timberrr** [comment]
Awesome thanks! I'll see if I can take a look today :) - I think batch scripts can be super finicky around quoted strings, so it may be there needs to be some extra quotes somewhere? Usually spaces breaking scripts is because it needs quotes, but that's only a guess until I can take a proper peek.


> Ok @timberrr I just sunk a bit over an hour _just_ trying to get things to work when you put the `vr` folder in a path that contains a space things actually work, but I couldn't figure it out. See above comment for more details. Things work flawlessly when the `vr` folder doesn't have a space in its path.
> 
> 
> 
> I'm hoping you'll be able to figure this out with fresh eyes. Literally _everything_ else is working perfectly and ready to push, lots of little enhancements that were enabled by your new install process, so I'm very excited to get this pushed out!

**Comment by monstermac77** [comment]
> Awesome thanks! I'll see if I can take a look today :) - I think batch scripts can be super finicky around quoted strings, so it may be there needs to be some extra quotes somewhere? Usually spaces breaking scripts is because it needs quotes, but that's only a guess until I can take a proper peek.

Yay, thanks so much! Yeah, I figure it’s something like the batch script or even the vbs script that needs extra quotes.

**Comment by timberrr** [comment]
Ok proposed fix for spaces in file paths included, 3 changes:
- install script adds quotes around the file path being added to the scheduled task (otherwise it's broken by whitespace and doesn't run the wrapper bat at all).
- There appears to be a "feature" that the Start command (which is what I presume the TS is using) can't handled both the script path AND arguments being quoted, so instead we still pass the argument folder path without quotes, which means any spaces in the file path act as passing multiple arguments (e.g. %1=C:\Program, %2=Files\Mixed, %3=VR etc etc):
- The wrapper bat then uses %* instead of %1 to take and concatenate all provided arguments, so basically any space in a file path is added back in as part of that
- Wrapper bat passes filepath to VBS in string quotes
- VBS includes extra escaped quotes in the strArgs variable so the actual shell run is `cmd /c "file path to bat"` to again allow for spaced files

Hopefully works ok for you too!

**Comment by monstermac77** [comment]
> Ok proposed fix for spaces in file paths included, 3 changes:
> 
> * install script adds quotes around the file path being added to the scheduled task (otherwise it's broken by whitespace and doesn't run the wrapper bat at all).
> * There appears to be a "feature" that the Start command (which is what I presume the TS is using) can't handled both the script path AND arguments being quoted, so instead we still pass the argument folder path without quotes, which means any spaces in the file path act as passing multiple arguments (e.g. %1=C:\Program, %2=Files\Mixed, %3=VR etc etc):
> * The wrapper bat then uses %* instead of %1 to take and concatenate all provided arguments, so basically any space in a file path is added back in as part of that
> * Wrapper bat passes filepath to VBS in string quotes
> * VBS includes extra escaped quotes in the strArgs variable so the actual shell run is `cmd /c "file path to bat"` to again allow for spaced files
> 
> Hopefully works ok for you too!

Fantastic work! I think I can safely say I never would have thought of that solution, the "let it explode, then implode it later" thing. Thank you again, the whole spaces in batch stuff really stresses me out (same with spaces in Bash). 

Works flawlessly for me. Just had to resolve a merge conflict, did a bunch more testing, and merged this all in. I'll be posting this as a new release shortly :)

**Pull request merged**
